### ISSUE TITLE
Main menu error in node 4.0

### ISSUE THREAD

**Issue by davgeek** [sethvincent/javascripting#128]
The main menu does not work when run with nodejs v4.0, only in version 0.12 and earlier.

**Comment by ojoaofernandes** [comment]
Here is ok.

![main-menu-javascripting](https://cloud.githubusercontent.com/assets/6754163/9835760/3a1949ba-59d1-11e5-9895-9bf735b36ef4.png)
![node-v](https://cloud.githubusercontent.com/assets/6754163/9835761/3a393f36-59d1-11e5-842b-57c38c72174f.png)

**Comment by SomeoneWeird** [comment]
@davgeek What OS are you on?

**Comment by calvinalx** [comment]
I can confirm it doesn't work.

I am on Windows 10 and Node 4.0.0. The arrow key doesn't work so I am stuck only on one sections which is Introductions.

**Comment by davgeek** [comment]
I am on Win10, @calvinalx yes the arrow heys doesn't work.

**Comment by uuaqarahmed** [comment]
Using node v4.0.0, tried to run both on command and powershell on Win10. The menu is not working and can't go beyond INTRODUCTION. 

![javascripting_menu](https://cloud.githubusercontent.com/assets/527591/9922339/c5a30414-5cef-11e5-8140-851ed9834f5f.png)
![power_shell](https://cloud.githubusercontent.com/assets/527591/9922340/c5a6bc3a-5cef-11e5-8bb0-8a97ec5f4862.png)

**Comment by SomeoneWeird** [comment]
https://github.com/nodeschool/discussions/issues/1448

**Comment by pungggi** [comment]
node 4 and above.. in 4.1.0 it doesnt work either

**Comment by liuzeyafzy** [comment]
Can't see the arrow on `CentOS release 6.5 (Final)` & `node v4.0.0`.
But I can choose `STRINGS` by click Down button twice.

**Comment by SomeoneWeird** [comment]
The node 4 bug only affects Windows.

**Comment by SomeoneWeird** [comment]
Fixed upstream in node 5.1.0
