### ISSUE TITLE
cant get to second excercise

### ISSUE THREAD

**Issue by jansteh** [sethvincent/javascripting#152]
the arrows are not working or I do not know how...

**Comment by SomeoneWeird** [comment]
Please update to at least node 5.1.0

**Comment by jansteh** [comment]
Hello, Thanks for the advice! Jan

**Comment by SomeoneWeird** [comment]
Did that fix your issue? :)

**Comment by jansteh** [comment]
well, not yet tried, I have it on my home comp. yesterday after i posted in
the forum i fooled around in the cmd and found a command in help. thanks to
that i continued thru to next exetcises. im gona put that into git forum
for others later. jan

**Comment by jansteh** [comment]
type in cmd: javascripting select NAME ......... Select a workshop. Substitute NAME with for example variables the second exercise.

**Comment by jansteh** [comment]
and updating to the latest version of node helped corrected the issue! thanks!
