### ISSUE TITLE
For Loop Error

### ISSUE THREAD

**Issue by Joel-Lumian** [sethvincent/javascripting#163]
I'm having an issue where my solution is the same as the expected answer, but I'm still getting an error message.

![screen shot 2016-03-15 at 2 38 22 am](https://cloud.githubusercontent.com/assets/15973292/13773549/02b0f13c-ea57-11e5-861b-35e26de2bbc8.png)

![screen shot 2016-03-15 at 2 36 21 am](https://cloud.githubusercontent.com/assets/15973292/13773504/bdcf5572-ea56-11e5-96ef-f26ad26ab7cf.png)

**Comment by SomeoneWeird** [comment]
The issue is that you're doing `console.log(total);` in the loop, which is causing it to log the `total` at each step. 

If you move that `console.log` line after the `for` loop has finished, it will work :)

**Comment by Joel-Lumian** [comment]
Thank you!
