### ISSUE TITLE
Does not work on Windows 8

### ISSUE THREAD

**Issue by kuba-orlik** [sethvincent/javascripting#168]
Running `javascripting` on Windows 8 causes the menu to display, but does not react to any keypresses... It happens in git bash, cmd, powershell and cygwin (in some of these cases the menu also lacks colors)

**Comment by martinheidegger** [comment]
Unfortunately this is a known issue with Node.js since Node 5.6 an older version should do the trick 😢  https://github.com/nodejs/node/issues/5384
