### ISSUE TITLE
javascripting command not found

### ISSUE THREAD

**Issue by monala** [sethvincent/javascripting#170]
i install javascripting  and after  writing javascripting show me javascripting command not found in mac os
how can i fix this issue?

**Comment by raslan3333** [comment]
انت عربية؟!
Am 12.06.2016 22:11 schrieb "mona" <notifications@github.com>:

**Comment by denysdovhan** [comment]
@monala don't you forget to install it with global flag `-g`? Like so:

```
npm install -g javascripting
```

**Comment by monala** [comment]
@denysdovhan  yes i use this command npm install -g javascripting

**Comment by monala** [comment]
@raslan3333  what?!!!

**Comment by denysdovhan** [comment]
@monala can you show the output from your terminal?

**Comment by monala** [comment]
@denysdovhan 
<img width="697" alt="screen shot 2016-06-13 at 12 55 36 am" src="https://cloud.githubusercontent.com/assets/16857813/15993631/9c006778-3101-11e6-8e32-0bdcb8b60c9f.png">

**Comment by denysdovhan** [comment]
@monala as I see, you have changed your npm prefix (modules folder). Maybe that's is the cause of problem.

**Comment by monala** [comment]
@denysdovhan i have problem with npm must use sudo for fix it i use this link https://docs.npmjs.com/getting-started/fixing-npm-permissions !

how i can solve this problem?

**Comment by denysdovhan** [comment]
@monala yes I know. Have no idea about fixing. Maybe someone else can help you. @sethvincent?

**Comment by monala** [comment]
@denysdovhan thanks for answering

**Comment by sethvincent** [comment]
@monala It looks like the `bin` folder in `~/.npm-packages` might not be in the PATH.

Make sure there's a line like this in your `~/.bash_profile` file:

```
 export PATH=~/.npm-packages/bin:$PATH
```

**Comment by sethvincent** [comment]
And also run `source ~/.bash_profile` after adding that line to make sure the change is available in your current terminal session.

**Comment by monala** [comment]
@sethvincent  thank you
i use this command npm bin
and after that 
 export PATH=~/.npm-packages/bin:$PATH
then 
alias npm-exec='PATH=$(npm bin):$PATH'
and now it works

**Comment by claudiopro** [comment]
@monala it seems you moved the default package install dir for node modules, but didn't add the new dir to the path. Also see the excellent recap on [using `npm install -g` without `sudo` by John Papa](https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/)

**Comment by monala** [comment]
@claudiopro it really help me.
tnx
