### ISSUE TITLE
Contextual errors/hints on failures.

### ISSUE THREAD

**Issue by SomeoneWeird** [sethvincent/javascripting#36]
I've started adding some example ones over [here](https://github.com/SomeoneWeird/javascripting/commit/bfc505423f6456c965df26ea46ec8dd75050a58c). I know it's pretty crude (those regexs are pretty horrible! :p). Just wanted to gauge peoples responses before I start adding more to all the other exercises and cleaning everything up.

Eg.

```js
$ cat a.js
var pizza = 'pizza is alright';
pizza.replace("alright", "wonderful");
console.log(pizza);
```
```
$ javascripting verify a.js
Nearly there! The replace function returns a new string, so make sure you assign the result to a variable!
-------------------
# O-oh, something isn't working.
But don't panic!
-------------------
Need help? Ask a question at: github.com/nodeschool/discussions/issues
```

**Comment by sethvincent** [comment]
Should this be closed now that we have the diff output for failure message?

**Comment by SomeoneWeird** [comment]
Yeah, I think so, it might be worth coming back to this in the future though.
