### ISSUE TITLE
javascripting not installing as a global variable

### ISSUE THREAD

**Issue by jhbrewer264** [sethvincent/javascripting#40]
Hi,

I followed the suggested commands for installing but even after installing the module 'javascripting'
fails to run as a global variable.  The error I receive when attempting to run it as a global variable is "/usr/bin/env: node: No such file or directory".

After receiving this error I attempted to move the module to /usr/bin/env from the directory it installed in (usr/local/lib/node_modules/javascripting).  Unfortunately, I was not able to move the files because /usr/bin/env is not a directory, rather it seems to be some sort of executable java file (usr/bin is a directory).

I am a bit lost and would love some advice on either how to install the module as a working global variable or whether there is another way to run the module without installing it as a global variable.

Thanks!

**Comment by SomeoneWeird** [comment]
If this is still an issue, reopen :)
