### ISSUE TITLE
Test for case-insensitivity and give hints

### ISSUE THREAD

**Issue by martinheidegger** [sethvincent/javascripting#41]
I got reminded in https://github.com/nodeschool/discussions/issues/700 that sometimes the problem occurs that people don't see the difference in their output. uppercase/lowercase etc. It might be good to check something like:

```JavaScript
function normalise(string) {
   return string.replace(/\.|\!|\?|\s|/g, "").toLowerCase()
}

function isProbablyTypo(expectedAnswer, answer) {
   return normalise(expectedAnswer) === normalise(answer)
}

if (isProbablyTypo(expectedAnswer, answer)) {
   console.log("Looks like you did the right thing but maybe you had a typo in there. We are a little picky to make sure that you understood the question. Maybe you want to check for typos?")
}
```

**Comment by SomeoneWeird** [comment]
Now that we have diff'ing in the latest javascripting, this shouldn't be much of an issue anymore. Going to close for now.
