### ISSUE TITLE
# O-oh, something isn't working.

### ISSUE THREAD

**Issue by rk08** [sethvincent/javascripting#44]
can you guys tell me why i am seeing this error...
for the functions task even i copied the code from solutions but still I am seeing this error.
can u help me in fixing it

C:\Users\Desktop\node-school> javascripting verify functions.js
-------------------
# O-oh, something isn't working.

But don't panic!

-------------------
Need help? Ask a question at: github.com/nodeschool/discussions/issues

**Comment by sethvincent** [comment]
Can you paste in your full solution?

Also, just in case: make sure to run `javascripting`, then select the functions challenge again, then run `javascripting verify functions.js`

Other troubleshooting:

- make sure you're in the correct folder, the same one that the functions.js file is in
- run `node functions.js` to see if the file executes like it should without running that verify command

**Comment by scarnago** [comment]
Same problem, I create everything ok, even check the solution but still getting "something isn't working", this was my solution for exercise 3 

var example = 'example string';
console.log(example.lenght);

**Comment by SomeoneWeird** [comment]
@scarnago You've misspelled `length` :)

**Comment by sethvincent** [comment]
We've recently done some work to improve the failure messages to be more helpful, so I think this can be closed. 

@rk08 & @scarnago if you are still having problems, feel free to reopen this or create a new issue.
