### ISSUE TITLE
TypeError when running javascripting

### ISSUE THREAD

**Issue by JamesRamm** [sethvincent/javascripting#62]
Installed node, installed javascripting, ran javascripting, got the blue menu, selected the first lesson and:

    TypeError: Object #(Transform) has no method 'destroy'

followed by a traceback..
Any ideas?

Running 32 bit node.js on Win 7

**Comment by sethvincent** [comment]
I'm not sure yet! I may need someone more experienced than I am with node + windows development to pitch in here.

Which prompt are you using when you install & run javascripting? cmd? Or something else?

**Comment by sethvincent** [comment]
Oh: it might be useful to see the traceback, too. Could you add a comment with that pasted in?

**Comment by JamesRamm** [comment]
cmd prompt, yes
Ill try and paste a screenshot of the traceback:

![image](https://cloud.githubusercontent.com/assets/2784823/6328350/6bd2cb00-bb5e-11e4-8e1c-1120431ed328.png)

**Comment by SomeoneWeird** [comment]
Is this still an issue?

**Comment by JamesRamm** [comment]
Yes, but Ive not had a chance to look back at it since. Never figured out what was wrong.

**Comment by SomeoneWeird** [comment]
Okay, quite a bit has changed since this issue was posted, if you still have the same error with the latest version of node & javascripting - reopen this :)
