### ISSUE TITLE
Change to workshopper

### ISSUE THREAD

**Issue by martinheidegger** [sethvincent/javascripting#64]
Hello @sethvincent I am asking even though I wonder if its futile: Do you think its hard to change the system to workshopper. The reason why I asked is: It is quite some work to translate the content into various languages. Changing to workshopper would make it easier to translate javascripting to other languages.

**Comment by ledsun** [comment]
:+1:

**Comment by SomeoneWeird** [comment]
I'd be +1 on this, i'd love to get rid of some of the hacks i've done.

**Comment by tai2** [comment]
:+1:

**Comment by martinheidegger** [comment]
Closing in favor of PR https://github.com/sethvincent/javascripting/pull/105
