### ISSUE TITLE
javascripting not running with io.js v1.4.1

### ISSUE THREAD

**Issue by alexfernandez** [sethvincent/javascripting#65]
Install and run:

    $ javascripting

Select the first adventure INTRODUCTION, fails with:

```
node: ../deps/uv/src/unix/stream.c:1174: uv_shutdown: Assertion `(stream->type == UV_TCP || stream->type == UV_NAMED_PIPE) && "uv_shutdown (unix) only supports uv_handle_t right now"' failed.
Aborted
```

Works fine with v0.12 though.

**Comment by SomeoneWeird** [comment]
I can't replicate this using iojs v1.4.3, can you try updating? Also, what OS are you on?

**Comment by alexfernandez** [comment]
I just replicated it with io.js v1.4.2, latest version installable using `nvm`, on Debian testing.

**Comment by SomeoneWeird** [comment]
Can't replicate with v1.4.2 on OSX. I don't have a debian box I can access at the moment, i'll try when i get home.

**Comment by SomeoneWeird** [comment]
@alexfernandez is this still a problem with the latest iojs?

**Comment by alexfernandez** [comment]
I'm not sure, I'll reopen if so. Thanks!
