### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by Angelfire** [sethvincent/javascripting#67]
After I do the installation:
```
npm install --global javascripting
```

Y try to run: *javascripting* in terminal

But terminal show me this error:
> /usr/bin/env: node: No such file or directory

**Comment by sethvincent** [comment]
Are you using ubuntu? That's an error that sometimes comes up.

If that's the case you probably have a `nodejs` command instead of `node`, and creating a symlink like this may solve the problem:

```
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by Angelfire** [comment]
Thank you very much @sethvincent, It works!!!
