### ISSUE TITLE
looping through arrays and accessing array values are in the wrong order

### ISSUE THREAD

**Issue by mwilykat** [sethvincent/javascripting#68]
well, that or the messages you get on success about what you're going to do next are in the wrong order for those two exercises.

also there's an extraneous ` in the console.log instruction line in accessing array values.

**Comment by SomeoneWeird** [comment]
Thanks! Not sure which way the problems are supposed to be, i'd have though that accessing values should come first, but i'll defer to @sethvincent 

Fixed the typo in 08cda154251012c77f5e5678af4cc3d7ad4769a2

**Comment by SomeoneWeird** [comment]
I think this is resolved.
