### ISSUE TITLE
looping-through-arrays.js solution bug?

### ISSUE THREAD

**Issue by sarahjbray** [sethvincent/javascripting#82]
I'm pretty sure I've got the looping through arrays code right, but I'm getting this error (there's no way the solution is supposed to be 45 if we're trying to get the array values to be plural, right?)

```
$ javascripting verify looping-through-arrays.js
-------------------
# O-oh, something isn't working.

# But don't panic!

-------------------
## Check your solution:

Solution
===================

45


Your Attempt
===================

[ 'cats', 'dogs', 'rats' ]


Difference
===================

[ 'cats', 'dogs', 'rats' ]45
```

My code was:
```
File: looping-through-arrays.js                        

var pets = ['cat', 'dog', 'rat'];
for (var i = 0; i < 3; i++) {
  pets[i] = pets[i] + 's';
}
console.log(pets);
```

Am I crazy? Possibly crazy.

**Comment by marocchino** [comment]
What is your `$ javascripting selected` result?
I think maybe you are not doing 'ACCESSING ARRAY VALUES'.

**Comment by SomeoneWeird** [comment]
I'm going to close this, if you're still having the same issue, reopen :)

**Comment by crlee3** [comment]
Your code worked perfectly. Check that you are on the right lesson. I've done the same thing but on a different lesson >.<
